# Generated by Django 5.0 on 2023-12-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True)),
                ('durations', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
