# Generated by Django 5.0 on 2023-12-06 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tasks_done'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='TasksModel',
        ),
    ]
