# Generated by Django 5.0 on 2023-12-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_tasksmodel_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksmodel',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
