# Generated by Django 5.0 on 2023-12-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_tasksmodel_about_alter_tasksmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksmodel',
            options={'ordering': ['-created']},
        ),
    ]
