# Generated by Django 5.0 on 2023-12-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_profilepicturemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicturemodel',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
