# Generated by Django 5.0 on 2023-12-14 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_groupmodel_membershipmodel_groupmodel_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinGroupRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('request_to_join', models.BooleanField(default=False, editable=False)),
                ('invitation', models.BooleanField(default=False, editable=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='todo.groupmodel')),
                ('invitor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitor', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
