# Generated by Django 5.0 on 2023-12-17 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_joingrouprequestmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='joingrouprequestmodel',
            old_name='user',
            new_name='invited',
        ),
        migrations.RenameField(
            model_name='membershipmodel',
            old_name='inviter',
            new_name='invitor',
        ),
        migrations.RemoveField(
            model_name='membershipmodel',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='joingrouprequestmodel',
            name='accepted',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='joingrouprequestmodel',
            name='invitor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitor', to=settings.AUTH_USER_MODEL),
        ),
    ]
