# Generated by Django 5.0 on 2023-12-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_profilepicturemodel_about_me_friendrequestmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='status',
            field=models.CharField(choices=[('S', 'Private'), ('F', 'Friends'), ('G', 'Groups'), ('P', 'Public')], default='F', max_length=1),
        ),
    ]
