# Generated by Django 5.0 on 2023-12-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_alter_tasksmodel_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksmodel',
            name='in_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todo.groupmodel'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='status',
            field=models.CharField(choices=[('S', 'Private'), ('F', 'Friends'), ('P', 'Public')], default='F', max_length=1),
        ),
    ]
