# Generated by Django 5.0 on 2023-12-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_rename_user_joingrouprequestmodel_invited_and_more'),
        ('todo', '0015_tasksmodel_in_group_alter_tasksmodel_status'),
    ]

    operations = [
    ]
