# Generated by Django 5.0 on 2023-12-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_groupmodel_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequestmodel',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('Y', 'accepted'), ('N', 'denied')], default='Pending', max_length=1),
        ),
    ]
